name: build-project
run-name: ${{ github.actor }} is building the project.
on: [push]
jobs:
  build-project:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node 
        uses: actions/setup-node@v2
        with:
		node-version: '18'

      - name: Install packages 
        run: npm install
      
      - name: Typescript to Javascript
        run: npx tsc