name: build-project
run-name: ${{ github.actor }} is building the project.
on:
  push:
    branches: [$default-branch]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-project:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install packages 
        run: npm install
      
      - name: Compile Typescript to Javascript
        run: npx tsc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
